/*
 * This source file was generated by the Gradle 'init' task
 */
package com.converter;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class App {
    public static void main(String[] args) {
        SpringApplication.run(App.class, args);
        System.out.println("Backend started at http://localhost:8080");
    }
}
